### ISSUE TITLE
More than 16 buttons

### ISSUE THREAD

**Issue by legomolina** [GAMELASTER/ArduinoGamepad#1]
Hi, is possible to add more than 16 buttons?

**Comment by gamelaster** [comment]
Hello, sure, it's possible, you just need to edit those lines to get more buttons:
https://github.com/gamelaster/ArduinoGamepad/blob/master/Gamepad.cpp#L37

**Comment by legomolina** [comment]
So, can I put:
`0x29, 0x20, //     USAGE_MAXIMUM (Button 32)`
?

**Comment by gamelaster** [comment]
Yes 😊
